/**
 * Canonical EWKB test fixtures.
 *
 * All hex strings were generated by encoding known coordinate values through
 * the same bit-level operations that PostGIS uses. Each fixture is documented
 * with its byte-layout so test failures are easy to trace.
 */

// ---------------------------------------------------------------------------
// Point fixtures
// ---------------------------------------------------------------------------

/**
 * POINT(2.3456789 48.8534843) SRID=4326, little-endian
 * Approximate location: Paris, France
 */
export const POINT_LE_4326 = '0101000020e61000008956934cf3c3024021133af93e6d4840';

/**
 * POINT(2.3456789 48.8534843) SRID=4326, big-endian
 */
export const POINT_BE_4326 = '0020000001000010e64002c3f34c93568940486d3ef93a1321';

/**
 * POINT(3.3792 6.5244) SRID=4326, little-endian
 * Approximate location: Lagos, Nigeria
 */
export const POINT_LAGOS_LE = '0101000020e6100000462575029a080b40f0164850fc181a40';

/**
 * POINT with SRID=32632 (UTM zone 32N) — invalid for our decoder.
 */
export const POINT_LE_WRONG_SRID = '0101000020787f00008956934cf3c3024021133af93e6d4840';

/**
 * Minimal valid Point: same Paris coordinates, used in truncation tests.
 */
export const POINT_PARIS_X = 2.3456789;
export const POINT_PARIS_Y = 48.8534843;

// ---------------------------------------------------------------------------
// LineString fixtures
// ---------------------------------------------------------------------------

/**
 * LINESTRING(0 0, 1 1, 2 2) SRID=4326, little-endian
 */
export const LS_3PT_LE = '0102000020e61000000300000000000000000000000000000000000000000000000000f03f000000000000f03f00000000000000400000000000000040';

/**
 * LINESTRING(0 0, 1 1, 2 2) SRID=4326, big-endian
 */
export const LS_3PT_BE = '0020000002000010e600000003000000000000000000000000000000003ff00000000000003ff000000000000040000000000000004000000000000000';

/**
 * LINESTRING(5.5 6.6) SRID=4326, little-endian — single-point degenerate
 */
export const LS_1PT_LE = '0102000020e61000000100000000000000000016406666666666661a40';

// ---------------------------------------------------------------------------
// Malformed / edge-case fixtures
// ---------------------------------------------------------------------------

/**
 * A Polygon EWKB with SRID 4326 — wrong geometry type for both decoders.
 */
export const WRONG_TYPE = '0103000020e610000000000000000000000000000000000000';

/**
 * WKB Point without SRID flag set — invalid for our EWKB decoder.
 */
export const NO_SRID_FLAG = '01010000008956934cf3c3024021133af93e6d4840';

/**
 * Invalid byte-order marker (0xFF instead of 0x00 or 0x01).
 */
export const BAD_BYTE_ORDER = 'ff000000000000000000000000000000000000000000000000';

// ---------------------------------------------------------------------------
// Builders for dynamic fixtures
// ---------------------------------------------------------------------------

const SRID_FLAG = 0x20000000;
const Z_FLAG = 0x80000000;
const M_FLAG = 0x40000000;

/**
 * Builds an EWKB Point Buffer from raw values (2D).
 */
export function buildPointBuffer(
  x: number,
  y: number,
  srid: number,
  littleEndian: boolean,
): Buffer {
  const buf = Buffer.alloc(25);
  buf.writeUInt8(littleEndian ? 1 : 0, 0);
  if (littleEndian) {
    buf.writeUInt32LE(1 + SRID_FLAG, 1);
    buf.writeUInt32LE(srid, 5);
    buf.writeDoubleLE(x, 9);
    buf.writeDoubleLE(y, 17);
  } else {
    buf.writeUInt32BE(1 + SRID_FLAG, 1);
    buf.writeUInt32BE(srid, 5);
    buf.writeDoubleBE(x, 9);
    buf.writeDoubleBE(y, 17);
  }
  return buf;
}

/**
 * Builds an EWKB LineString Buffer from a coordinate array (2D).
 */
export function buildLineStringBuffer(
  coords: Array<[number, number]>,
  srid: number,
  littleEndian: boolean,
): Buffer {
  const n = coords.length;
  const buf = Buffer.alloc(13 + n * 16);
  buf.writeUInt8(littleEndian ? 1 : 0, 0);
  if (littleEndian) {
    buf.writeUInt32LE(2 + SRID_FLAG, 1);
    buf.writeUInt32LE(srid, 5);
    buf.writeUInt32LE(n, 9);
    for (let i = 0; i < n; i++) {
      const coord = coords[i];
      if (coord === undefined) continue;
      buf.writeDoubleLE(coord[0], 13 + i * 16);
      buf.writeDoubleLE(coord[1], 13 + i * 16 + 8);
    }
  } else {
    buf.writeUInt32BE(2 + SRID_FLAG, 1);
    buf.writeUInt32BE(srid, 5);
    buf.writeUInt32BE(n, 9);
    for (let i = 0; i < n; i++) {
      const coord = coords[i];
      if (coord === undefined) continue;
      buf.writeDoubleBE(coord[0], 13 + i * 16);
      buf.writeDoubleBE(coord[1], 13 + i * 16 + 8);
    }
  }
  return buf;
}

/**
 * Generates a large LineString with `n` evenly-spaced coordinates.
 */
export function buildLargeLineString(n: number): Buffer {
  const coords: Array<[number, number]> = Array.from(
    { length: n },
    (_, i) => [i * 0.01, i * 0.005],
  );
  return buildLineStringBuffer(coords, 4326, true);
}

// ---------------------------------------------------------------------------
// 3D/4D/Polygon/Collection Builders
// ---------------------------------------------------------------------------

export interface FixtureCoord {
  lng: number;
  lat: number;
  z?: number;
  m?: number;
}

function writeRawCoordinate(
  buf: Buffer,
  offset: number,
  c: FixtureCoord,
  le: boolean,
  hasZ: boolean,
  hasM: boolean,
): number {
  if (le) {
    buf.writeDoubleLE(c.lng, offset);
    buf.writeDoubleLE(c.lat, offset + 8);
    let o = offset + 16;
    if (hasZ) {
      buf.writeDoubleLE(c.z ?? 0, o);
      o += 8;
    }
    if (hasM) {
      buf.writeDoubleLE(c.m ?? 0, o);
      o += 8;
    }
    return o;
  } else {
    buf.writeDoubleBE(c.lng, offset);
    buf.writeDoubleBE(c.lat, offset + 8);
    let o = offset + 16;
    if (hasZ) {
      buf.writeDoubleBE(c.z ?? 0, o);
      o += 8;
    }
    if (hasM) {
      buf.writeDoubleBE(c.m ?? 0, o);
      o += 8;
    }
    return o;
  }
}

export function buildPointBuffer3D4D(
  c: FixtureCoord,
  srid: number,
  le: boolean,
  hasZ: boolean,
  hasM: boolean,
): Buffer {
  const stride = 16 + (hasZ ? 8 : 0) + (hasM ? 8 : 0);
  const buf = Buffer.alloc(9 + stride);
  buf.writeUInt8(le ? 1 : 0, 0);

  let type = 1 + SRID_FLAG;
  if (hasZ) type += Z_FLAG;
  if (hasM) type += M_FLAG;

  if (le) {
    buf.writeUInt32LE(type, 1);
    buf.writeUInt32LE(srid, 5);
  } else {
    buf.writeUInt32BE(type, 1);
    buf.writeUInt32BE(srid, 5);
  }

  writeRawCoordinate(buf, 9, c, le, hasZ, hasM);
  return buf;
}

export function buildLineStringBuffer3D4D(
  coords: FixtureCoord[],
  srid: number,
  le: boolean,
  hasZ: boolean,
  hasM: boolean,
): Buffer {
  const stride = 16 + (hasZ ? 8 : 0) + (hasM ? 8 : 0);
  const buf = Buffer.alloc(13 + coords.length * stride);
  buf.writeUInt8(le ? 1 : 0, 0);

  let type = 2 + SRID_FLAG;
  if (hasZ) type += Z_FLAG;
  if (hasM) type += M_FLAG;

  if (le) {
    buf.writeUInt32LE(type, 1);
    buf.writeUInt32LE(srid, 5);
    buf.writeUInt32LE(coords.length, 9);
  } else {
    buf.writeUInt32BE(type, 1);
    buf.writeUInt32BE(srid, 5);
    buf.writeUInt32BE(coords.length, 9);
  }

  let offset = 13;
  for (const c of coords) {
    offset = writeRawCoordinate(buf, offset, c, le, hasZ, hasM);
  }
  return buf;
}

export function buildPolygonBuffer(
  rings: FixtureCoord[][],
  srid: number,
  le: boolean,
  hasZ: boolean,
  hasM: boolean,
): Buffer {
  const stride = 16 + (hasZ ? 8 : 0) + (hasM ? 8 : 0);
  let totalSize = 13; // header + numRings
  for (const ring of rings) {
    totalSize += 4 + ring.length * stride;
  }

  const buf = Buffer.alloc(totalSize);
  buf.writeUInt8(le ? 1 : 0, 0);

  let type = 3 + SRID_FLAG;
  if (hasZ) type += Z_FLAG;
  if (hasM) type += M_FLAG;

  if (le) {
    buf.writeUInt32LE(type, 1);
    buf.writeUInt32LE(srid, 5);
    buf.writeUInt32LE(rings.length, 9);
  } else {
    buf.writeUInt32BE(type, 1);
    buf.writeUInt32BE(srid, 5);
    buf.writeUInt32BE(rings.length, 9);
  }

  let offset = 13;
  for (const ring of rings) {
    if (le) {
      buf.writeUInt32LE(ring.length, offset);
    } else {
      buf.writeUInt32BE(ring.length, offset);
    }
    offset += 4;
    for (const c of ring) {
      offset = writeRawCoordinate(buf, offset, c, le, hasZ, hasM);
    }
  }
  return buf;
}

export function buildMultiPointBuffer(
  coords: FixtureCoord[],
  srid: number,
  le: boolean,
  hasZ: boolean,
  hasM: boolean,
): Buffer {
  const stride = 16 + (hasZ ? 8 : 0) + (hasM ? 8 : 0);
  // MultiPoint header = 13 bytes.
  // Each point element: byteOrder (1) + type (4) [no srid] + coords (stride) = 5 + stride
  const ptSize = 5 + stride;
  const buf = Buffer.alloc(13 + coords.length * ptSize);
  buf.writeUInt8(le ? 1 : 0, 0);

  let type = 4 + SRID_FLAG;
  if (hasZ) type += Z_FLAG;
  if (hasM) type += M_FLAG;

  if (le) {
    buf.writeUInt32LE(type, 1);
    buf.writeUInt32LE(srid, 5);
    buf.writeUInt32LE(coords.length, 9);
  } else {
    buf.writeUInt32BE(type, 1);
    buf.writeUInt32BE(srid, 5);
    buf.writeUInt32BE(coords.length, 9);
  }

  let offset = 13;
  let ptType = 1; // Point, no SRID flag set
  if (hasZ) ptType += Z_FLAG;
  if (hasM) ptType += M_FLAG;

  for (const c of coords) {
    buf.writeUInt8(le ? 1 : 0, offset);
    if (le) {
      buf.writeUInt32LE(ptType, offset + 1);
    } else {
      buf.writeUInt32BE(ptType, offset + 1);
    }
    writeRawCoordinate(buf, offset + 5, c, le, hasZ, hasM);
    offset += ptSize;
  }
  return buf;
}

export function buildMultiLineStringBuffer(
  lines: FixtureCoord[][],
  srid: number,
  le: boolean,
  hasZ: boolean,
  hasM: boolean,
): Buffer {
  const stride = 16 + (hasZ ? 8 : 0) + (hasM ? 8 : 0);
  let totalSize = 13;
  for (const line of lines) {
    totalSize += 5 + 4 + line.length * stride; // header (5) + numPoints (4) + points
  }

  const buf = Buffer.alloc(totalSize);
  buf.writeUInt8(le ? 1 : 0, 0);

  let type = 5 + SRID_FLAG;
  if (hasZ) type += Z_FLAG;
  if (hasM) type += M_FLAG;

  if (le) {
    buf.writeUInt32LE(type, 1);
    buf.writeUInt32LE(srid, 5);
    buf.writeUInt32LE(lines.length, 9);
  } else {
    buf.writeUInt32BE(type, 1);
    buf.writeUInt32BE(srid, 5);
    buf.writeUInt32BE(lines.length, 9);
  }

  let offset = 13;
  let lineType = 2; // LineString, no SRID flag set
  if (hasZ) lineType += Z_FLAG;
  if (hasM) lineType += M_FLAG;

  for (const line of lines) {
    buf.writeUInt8(le ? 1 : 0, offset);
    if (le) {
      buf.writeUInt32LE(lineType, offset + 1);
      buf.writeUInt32LE(line.length, offset + 5);
    } else {
      buf.writeUInt32BE(lineType, offset + 1);
      buf.writeUInt32BE(line.length, offset + 5);
    }
    offset += 9;
    for (const c of line) {
      offset = writeRawCoordinate(buf, offset, c, le, hasZ, hasM);
    }
  }
  return buf;
}

export function buildMultiPolygonBuffer(
  polygons: FixtureCoord[][][],
  srid: number,
  le: boolean,
  hasZ: boolean,
  hasM: boolean,
): Buffer {
  const stride = 16 + (hasZ ? 8 : 0) + (hasM ? 8 : 0);
  let totalSize = 13;
  for (const poly of polygons) {
    totalSize += 5 + 4; // header (5) + numRings (4)
    for (const ring of poly) {
      totalSize += 4 + ring.length * stride; // numPoints (4) + points
    }
  }

  const buf = Buffer.alloc(totalSize);
  buf.writeUInt8(le ? 1 : 0, 0);

  let type = 6 + SRID_FLAG;
  if (hasZ) type += Z_FLAG;
  if (hasM) type += M_FLAG;

  if (le) {
    buf.writeUInt32LE(type, 1);
    buf.writeUInt32LE(srid, 5);
    buf.writeUInt32LE(polygons.length, 9);
  } else {
    buf.writeUInt32BE(type, 1);
    buf.writeUInt32BE(srid, 5);
    buf.writeUInt32BE(polygons.length, 9);
  }

  let offset = 13;
  let polyType = 3; // Polygon, no SRID flag set
  if (hasZ) polyType += Z_FLAG;
  if (hasM) polyType += M_FLAG;

  for (const poly of polygons) {
    buf.writeUInt8(le ? 1 : 0, offset);
    if (le) {
      buf.writeUInt32LE(polyType, offset + 1);
      buf.writeUInt32LE(poly.length, offset + 5);
    } else {
      buf.writeUInt32BE(polyType, offset + 1);
      buf.writeUInt32BE(poly.length, offset + 5);
    }
    offset += 9;

    for (const ring of poly) {
      if (le) {
        buf.writeUInt32LE(ring.length, offset);
      } else {
        buf.writeUInt32BE(ring.length, offset);
      }
      offset += 4;
      for (const c of ring) {
        offset = writeRawCoordinate(buf, offset, c, le, hasZ, hasM);
      }
    }
  }
  return buf;
}
